### ISSUE TITLE
Avoid including react in lib and allow simple import of lib

### ISSUE THREAD

**Issue by enjoylife** [Gattermeier/LazyImage#4]
Currently the lib is including react in its outputed index.js 

```
npm install lazyimage
```

And the following outputs an empty object instead of the LazyImage component.

```
import LazyImage from 'lazyimage';
console.log(LazyImage) // empty object
```

**Comment by Gattermeier** [comment]
Good catch, thanks @enjoylife , I will look at it.

**Comment by Gattermeier** [comment]
Should be fixed.
